import "./elements/announcements/announcements";
import "./elements/barcode/barcode";
import "./elements/daily-timetable/daily-timetable";
import "./elements/extensions/extensions";
import "./elements/extensions-marketplace/extensions-marketplace";
import "./elements/info/info";
import "./elements/loader/loader";
import "./elements/notification/notification";
import "./elements/navbar/navbar";
import "./elements/settings/settings"
import "./elements/timetable/timetable";