import { Time } from "./utils";

export type BaseBell = {
    name: string,
    shortName: string,
    startTime: Time,
    endTime: Time,
    shouldDisplay: boolean
};

export type Bell = BaseBell & {
    type: "bell"
};

export type Period = BaseBell & {
    type: "period",
    periodIndex: number,
    room: string,
    roomChanged: boolean,
    teacher: string | null,
    teacherChanged: boolean
};

export type DailyTimetable = {
    date: string,
    dayNumber: number,
    dayName: string,
    autoGenerated?: boolean,
    timetable: (Bell | Period)[]
};
